global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape cAdvisor untuk metrik Docker container (CPU, RAM, dll)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Scrape Prometheus sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
